#!/usr/bin/env node
import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE_URL = 'https://publicsuffix.org/list/public_suffix_list.dat';
const GENERATED_AT = '2026-07-26';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const outPath = resolve(repoRoot, 'core', 'crates', 'safety-core', 'src', 'psl_data.rs');

const response = await fetch(SOURCE_URL);
if (!response.ok) {
  throw new Error(`failed to fetch PSL: ${response.status} ${response.statusText}`);
}
const text = await response.text();
const begin = text.indexOf('// ===BEGIN ICANN DOMAINS===');
const end = text.indexOf('// ===END ICANN DOMAINS===');
if (begin === -1 || end === -1 || end <= begin) {
  throw new Error('ICANN section markers not found in PSL');
}
const icann = text.slice(begin, end);
const exact = new Set();
const wildcard = new Set();
const exception = new Set();

for (const rawLine of icann.split(/\r?\n/)) {
  const line = rawLine.trim().toLowerCase();
  if (!line || line.startsWith('//')) continue;
  const bare = line.replace(/^!/, '').replace(/^\*\./, '');
  const labels = bare.split('.').filter(Boolean);
  const isNoRule = bare === 'no' || bare.endsWith('.no');
  const keep = line.startsWith('*.') || line.startsWith('!') || labels.length > 1 || isNoRule;
  if (!keep) continue;
  if (line.startsWith('!')) {
    exception.add(line.slice(1));
  } else if (line.startsWith('*.')) {
    wildcard.add(line.slice(2));
  } else {
    exact.add(line);
  }
}

const byLabelsThenLexical = (a, b) => {
  const diff = a.split('.').length - b.split('.').length;
  return diff || a.localeCompare(b);
};

function rustArray(name, values) {
  const lines = [...values].sort(byLabelsThenLexical).map((value) => `    ${JSON.stringify(value)},`);
  return `pub const ${name}: &[&str] = &[\n${lines.join('\n')}\n];\n`;
}

const output = `// Generated by tools/generate-psl.mjs on ${GENERATED_AT}.\n// Source: ${SOURCE_URL}\n//\n// Deliberately includes only the ICANN section. PRIVATE PSL rules such as github.io\n// are excluded because qrrrgh uses registrable domains for brand comparison, not\n// browser cookie scoping; including PRIVATE rules would fragment shared providers.\n// The default PSL rule (*) is implemented in psl.rs, so this table keeps only\n// multi-label rules, wildcard rules, exception rules, and all .no ICANN rules.\n\n${rustArray('EXACT_RULES', exact)}\n${rustArray('WILDCARD_RULES', wildcard)}\n${rustArray('EXCEPTION_RULES', exception)}`;
await writeFile(outPath, output, 'utf8');
console.log(`wrote ${outPath}`);
console.log(`exact=${exact.size} wildcard=${wildcard.size} exception=${exception.size}`);
